[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  # Timeout setting removed due to invalid syntax. To set timeouts, use per-function configuration if needed.

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Environment variables for production
[context.production.environment]
  # These will be set in Netlify dashboard
  GEMINI_API_KEY = ""
  OPENROUTER_API_KEY = ""

# Environment variables for deploy previews
[context.deploy-preview.environment]
  # These will be set in Netlify dashboard
  GEMINI_API_KEY = ""
  OPENROUTER_API_KEY = ""