
[build]
command = "npm run build"
publish = "dist"


[functions]
directory = "netlify/functions"
timeout = 60


[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200


[build.environment]
NODE_VERSION = "18"


# Environment variables for production
[context.production.environment]
GEMINI_API_KEY = ""
OPENROUTER_API_KEY = ""


# Environment variables for deploy previews
[context.deploy-preview.environment]
GEMINI_API_KEY = ""
OPENROUTER_API_KEY = ""